[package]
name = "rustpython_doc_db"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = false
license-file = "LICENSE"

[dependencies]

[lints]
workspace = true
